# Run both source and persisted bytecode through the existing VM.
set(not_source "${DOC_EXAMPLE_DIR}/logical_not.tap")
foreach(mode IN ITEMS source bytecode)
    if(mode STREQUAL "source")
        set(not_command "${not_source}")
    else()
        execute_process(COMMAND "${TAPAS}" -c "${not_source}"
            RESULT_VARIABLE not_compile)
        if(NOT not_compile EQUAL 0)
            message(FATAL_ERROR "not bytecode compilation failed")
        endif()
        set(not_command -e "${not_source}c")
    endif()
    execute_process(COMMAND "${TAPAS}" ${not_command}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT output STREQUAL "not: ok\n")
        message(FATAL_ERROR "not ${mode} failed: ${output}${error}")
    endif()
endforeach()
file(REMOVE "${not_source}c")
foreach(fixture IN ITEMS number string array union rule instance keyword missing operand_parentheses)
    execute_process(COMMAND "${TAPAS}" -c "${COMPILE_INVALID_DIR}/not_${fixture}.tap"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0 OR NOT error MATCHES "Compile Error")
        message(FATAL_ERROR "not ${fixture} should fail compilation: ${output}${error}")
    endif()
endforeach()
foreach(fixture IN ITEMS dynamic instance_dynamic error)
    set(not_invalid "${RUNTIME_INVALID_DIR}/not_${fixture}.tap")
    execute_process(COMMAND "${TAPAS}" -c "${not_invalid}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "not ${fixture} should compile: ${output}${error}")
    endif()
    foreach(mode IN ITEMS source bytecode)
        if(mode STREQUAL "source")
            set(not_command "${not_invalid}")
        else()
            set(not_command -e "${not_invalid}c")
        endif()
        execute_process(COMMAND "${TAPAS}" ${not_command}
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
        if(result EQUAL 0 OR NOT error MATCHES "Runtime Error")
            message(FATAL_ERROR "not ${fixture} ${mode} must fail: ${output}${error}")
        endif()
    endforeach()
    file(REMOVE "${not_invalid}c")
endforeach()
