set(domains_source "${REGRESSION_DIR}/rule_domains.tap")
execute_process(COMMAND "${TAPAS}" -c "${domains_source}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Domain bytecode compilation failed")
endif()
foreach(mode IN ITEMS source bytecode)
    if(mode STREQUAL "source")
        set(domains_command "${domains_source}")
    else()
        set(domains_command -e "${domains_source}c")
    endif()
    execute_process(COMMAND "${TAPAS}" ${domains_command}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT output STREQUAL "rule domains: ok\n")
        message(FATAL_ERROR "Domain ${mode} failed: ${output}${error}")
    endif()
endforeach()
file(REMOVE "${domains_source}c")
foreach(fixture IN ITEMS points_type points_enum range_float annotation arity)
    execute_process(COMMAND "${TAPAS}" -c "${COMPILE_INVALID_DIR}/domain_${fixture}.tap"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0 OR NOT error MATCHES "Compile Error")
        message(FATAL_ERROR "domain ${fixture} must fail compilation: ${output}${error}")
    endif()
endforeach()
foreach(fixture IN ITEMS reversed points_type range_type annotation argument return assignment)
    execute_process(COMMAND "${TAPAS}" "${RUNTIME_INVALID_DIR}/domain_${fixture}.tap"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0 OR NOT error MATCHES "Runtime Error")
        message(FATAL_ERROR "domain ${fixture} must fail at runtime: ${output}${error}")
    endif()
endforeach()
execute_process(COMMAND "${TAPAS}" "${SUPPORT_FIXTURE_DIR}/domain_serialize.tap"
    RESULT_VARIABLE result OUTPUT_VARIABLE serialized ERROR_VARIABLE error)
if(NOT result EQUAL 0 OR NOT serialized MATCHES "^TPIR6;")
    message(FATAL_ERROR "Domain serialization failed: ${error}")
endif()
string(STRIP "${serialized}" serialized)
set(restore_file "${CMAKE_CURRENT_BINARY_DIR}/domain_restore.tap")
file(WRITE "${restore_file}" "let R = rules::deserialize('${serialized}')\nassert(R(4))\nassert(rule { not R(9); not R(2) })\n")
execute_process(COMMAND "${TAPAS}" "${restore_file}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(REMOVE "${restore_file}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Domain fresh-process restoration failed: ${output}${error}")
endif()
