set(restrict_source "${REGRESSION_DIR}/rule_restrict.tap")
execute_process(COMMAND "${TAPAS}" -c "${restrict_source}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "restrict compilation failed")
endif()
foreach(mode IN ITEMS source bytecode)
    if(mode STREQUAL "source")
        set(restrict_command "${restrict_source}")
    else()
        set(restrict_command -e "${restrict_source}c")
    endif()
    execute_process(COMMAND "${TAPAS}" ${restrict_command}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT output MATCHES "restrict: ok")
        message(FATAL_ERROR "restrict ${mode} failed: ${output}${error}")
    endif()
endforeach()
file(REMOVE "${restrict_source}c")
foreach(fixture IN ITEMS name value range points key)
    execute_process(COMMAND "${TAPAS}" "${RUNTIME_INVALID_DIR}/restrict_${fixture}.tap"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0 OR NOT error MATCHES "Runtime Error")
        message(FATAL_ERROR "restrict ${fixture} should be rejected: ${output}${error}")
    endif()
endforeach()
