set(logic_source "${REGRESSION_DIR}/rule_logic.tap")
execute_process(COMMAND "${TAPAS}" -c "${logic_source}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Rule logic bytecode compilation failed")
endif()
foreach(mode IN ITEMS source bytecode)
    if(mode STREQUAL "source")
        set(logic_command "${logic_source}")
    else()
        set(logic_command -e "${logic_source}c")
    endif()
    execute_process(COMMAND "${TAPAS}" ${logic_command}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT output STREQUAL "rule logic: ok\n")
        message(FATAL_ERROR "Rule logic ${mode} failed: ${output}${error}")
    endif()
endforeach()
file(REMOVE "${logic_source}c")
foreach(fixture IN ITEMS logic_outside logic_function logic_number logic_rule bare_rule retired_require)
    execute_process(COMMAND "${TAPAS}" -c "${COMPILE_INVALID_DIR}/${fixture}.tap"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0 OR NOT error MATCHES "Compile Error")
        message(FATAL_ERROR "${fixture} must fail compilation: ${output}${error}")
    endif()
endforeach()
foreach(fixture IN ITEMS left_error right_error dynamic_type called_function builder_type recursion)
    execute_process(COMMAND "${TAPAS}" "${RUNTIME_INVALID_DIR}/logic_${fixture}.tap"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0 OR NOT error MATCHES "Runtime Error")
        message(FATAL_ERROR "logic ${fixture} must fail at runtime: ${output}${error}")
    endif()
endforeach()
execute_process(COMMAND "${TAPAS}" "${SUPPORT_FIXTURE_DIR}/logic_serialize.tap"
    RESULT_VARIABLE result OUTPUT_VARIABLE serialized ERROR_VARIABLE error)
if(NOT result EQUAL 0 OR NOT serialized MATCHES "^TPIR5;")
    message(FATAL_ERROR "Logic serialization failed: ${error}")
endif()
string(STRIP "${serialized}" serialized)
set(restore_file "${CMAKE_CURRENT_BINARY_DIR}/logic_restore.tap")
file(WRITE "${restore_file}" "let R = rules::deserialize('${serialized}')\nlet Yes = rule { true }\nlet No = rule { false }\nassert(R(No(), Yes()))\n")
execute_process(COMMAND "${TAPAS}" "${restore_file}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(REMOVE "${restore_file}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Logic fresh-process restoration failed: ${output}${error}")
endif()
