set(rule_not_source "${REGRESSION_DIR}/rule_not.tap")
execute_process(COMMAND "${TAPAS}" -c "${rule_not_source}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Rule not bytecode compilation failed")
endif()
foreach(mode IN ITEMS source bytecode)
    if(mode STREQUAL "source")
        set(rule_not_command "${rule_not_source}")
    else()
        set(rule_not_command -e "${rule_not_source}c")
    endif()
    execute_process(COMMAND "${TAPAS}" ${rule_not_command}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT output STREQUAL "rule not: ok\n")
        message(FATAL_ERROR "Rule not ${mode} failed: ${output}${error}")
    endif()
endforeach()
file(REMOVE "${rule_not_source}c")
foreach(fixture IN ITEMS rule number function_scope)
    execute_process(COMMAND "${TAPAS}" -c "${COMPILE_INVALID_DIR}/rule_not_${fixture}.tap"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0 OR NOT error MATCHES "Compile Error")
        message(FATAL_ERROR "Rule not ${fixture} must fail compilation: ${output}${error}")
    endif()
endforeach()
foreach(fixture IN ITEMS error dynamic_type recursion extension builder_type called_function)
    execute_process(COMMAND "${TAPAS}" "${RUNTIME_INVALID_DIR}/rule_not_${fixture}.tap"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0 OR NOT error MATCHES "Runtime Error")
        message(FATAL_ERROR "Rule not ${fixture} must fail at runtime: ${output}${error}")
    endif()
endforeach()

execute_process(COMMAND "${TAPAS}" "${SUPPORT_FIXTURE_DIR}/not_serialize.tap"
    RESULT_VARIABLE result OUTPUT_VARIABLE serialized ERROR_VARIABLE error)
if(NOT result EQUAL 0 OR NOT serialized MATCHES "^TPIR4;")
    message(FATAL_ERROR "Not serialization failed: ${error}")
endif()
string(STRIP "${serialized}" serialized)
set(restore_file "${CMAKE_CURRENT_BINARY_DIR}/not_restore.tap")
file(WRITE "${restore_file}" "let R = rules::deserialize('${serialized}')\nlet Child = rule { false }\nassert(R(Child()))\n")
execute_process(COMMAND "${TAPAS}" "${restore_file}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(REMOVE "${restore_file}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Not fresh-process restoration failed: ${output}${error}")
endif()
