set(expression_ir_source "${REGRESSION_DIR}/rule_expression_ir.tap")
execute_process(COMMAND "${TAPAS}" -c "${expression_ir_source}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Structured expression IR compilation failed")
endif()
foreach(mode IN ITEMS source bytecode)
    if(mode STREQUAL "source")
        set(expression_ir_command "${expression_ir_source}")
    else()
        set(expression_ir_command -e "${expression_ir_source}c")
    endif()
    execute_process(COMMAND "${TAPAS}" ${expression_ir_command}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT output MATCHES "rule expression IR: ok")
        message(FATAL_ERROR "Structured expression IR ${mode} failed: ${output}${error}")
    endif()
endforeach()
file(REMOVE "${expression_ir_source}c")
execute_process(COMMAND "${TAPAS}" "${RUNTIME_INVALID_DIR}/expression_ir_short_circuit.tap"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(result EQUAL 0 OR NOT error MATCHES "short-circuited")
    message(FATAL_ERROR "Skipped expression must not be replayed: ${output}${error}")
endif()
